#!/bin/bash
# Create a bootable ISO Hackintosh
# Mac OS X Install DVD
# Copyright (c) 2026 chris1111 All rights reserved.

# Unmount the dmg image
diskutil eject /Volumes/Mac-OSX-Install-DVD

# Resize the partition in the sparse bundle to remove any free space
hdiutil resize -size `hdiutil resize -limits /Private/tmp/MacOS.sparseimage | tail -n 1 | awk '{ print $1 }'`b /Private/tmp/MacOS.sparseimage

Sleep 2
# Mount the dmg image
hdiutil attach /Private/tmp/MacOS.sparseimage -noverify -nobrowse -mountpoint /Volumes/Mac-OSX-Install-DVD

echo " "
echo "**********************************************  "
echo "Create iso image! "   
echo "**********************************************  "
echo " "
# Create ISO image
hdiutil makehybrid -o "$HOME/Desktop/Mac OS X Install DVD.iso" "/Volumes/Mac-OSX-Install-DVD" -iso -hfs -joliet -eltorito-boot "/Volumes/Mac-OSX-Install-DVD/usr/standalone/i386/cdboot" -no-emul-boot -hfs-volume-name "Mac OS X Install DVD" -joliet-volume-name "Mac OS X Install DVD"

echo "**********************************************  "
echo "Unmount Installer image!  "
echo "**********************************************  "
Sleep 1
diskutil eject /Volumes/Installer-OS
Sleep 1
diskutil eject /Volumes/"Mac-OSX-Install-DVD"
Sleep 3

# Remove dmg
rm -rf /Private/tmp/MacOS.sparseimage

echo "  "
echo "**********************************************  "
echo "Mount Mac OS X Install DVD!  "   
echo "**********************************************  "
Open -R ~/Desktop/"Mac OS X Install DVD.iso"

echo "**********************************************  "
echo "Mac OS X Install DVD Done !  "
echo "**********************************************  "

exit