#!/bin/bash
# Create a bootable ISO Hackintosh
# Mac OS X Install DVD
# Copyright (c) 2026 chris1111 All rights reserved.

if [[ $(mount | awk '$3 == "/Volumes/Mac-OSX-Install-DVD" {print $3}') != "" ]]; then
 hdiutil detach -Force "/Volumes/Mac-OSX-Install-DVD"
fi

if [[ -d "/Volumes/Mac OS X Install DVD" ]]; then
 hdiutil detach -Force "/Volumes/Mac OS X Install DVD"
fi

if [ "/Private/tmp/Mac-OSX.sparseimage" ]; then
	rm -rf "/Private/tmp/MacOS.sparseimage"
fi

if [ "/$HOME/Desktop/Mac OS X Install DVD.iso" ]; then
	rm -rf "/$HOME/Desktop/Mac OS X Install DVD.iso"
fi

# Attach macOS Installer
hdiutil attach /Applications/Install\ Mac\ OS\ X\ Lion.app/Contents/SharedSupport/InstallESD.dmg -noverify -nobrowse -mountpoint /Volumes/Installer-OS  


# Convert the BaseSystem
FILE=/Volumes/Installer-OS/BaseSystem.dmg
if [ -f "$FILE" ]; then
    echo "$FILE exists."
    hdiutil convert /Volumes/Installer-OS/BaseSystem.dmg -format UDSP -o /Private/tmp/MacOS
fi

# Increase the sparse bundle capacity
hdiutil resize -size 8g /Private/tmp/MacOS.sparseimage

# Mount the sparse bundle for package addition
hdiutil attach /Private/tmp/MacOS.sparseimage -noverify -nobrowse -mountpoint /Volumes/Mac-OSX-Install-DVD

echo "  "
echo "**********************************************  "
echo "Copying Essentiel!  "   
echo "**********************************************  "

# Copying Essentiel
FILE=/Volumes/Installer-OS/mach_kernel
if [ -f "$FILE" ]; then
    echo "$FILE exists."
    cp -Rp /Volumes/Installer-OS/mach_kernel /Volumes/Mac-OSX-Install-DVD
fi

FILE=/Volumes/Installer-OS/BaseSystem.chunklist
if [ -f "$FILE" ]; then
    echo "$FILE exists."
    cp -Rp /Volumes/Installer-OS/BaseSystem.chunklist /Volumes/Mac-OSX-Install-DVD
fi

FILE=/Volumes/Installer-OS/BaseSystem.dmg
if [ -f "$FILE" ]; then
    echo "$FILE exists."
    cp -Rp /Volumes/Installer-OS/BaseSystem.dmg /Volumes/Mac-OSX-Install-DVD
fi

echo "Copying Packages! Wait . . ."
rm -rf "/Volumes/Mac-OSX-Install-DVD/System/Installation/Packages"
cp -Rp /Volumes/Installer-OS/Packages /Volumes/Mac-OSX-Install-DVD/System/Installation/Packages

exit