title: Lion-DVD-Creator
description: Script to create a bootable Lion DVD and installing Chameleon
github: 
  repository_url: https://github.com/chris1111/Lion-DVD-Creator
remote_theme: chris1111/cayman-dark
