#!/bin/bash
# Installer Mac OS X Lion
# (c) Copyright 2026 chris1111 
# This will install Chameleon to the SSD
PARENTDIR=$(dirname "$0")
cd "$PARENTDIR"

diskutil list

#get Bootloader Installer path
if [ "$2" == "" ]; then

echo  "`tput setaf 7``tput sgr0``tput bold``tput setaf 10`Type the disk number then press Enter.`tput sgr0` `tput setaf 7``tput sgr0`  "
echo  "Exemple: -> `tput setaf 7``tput sgr0``tput bold``tput setaf 10`disk3`tput sgr0` `tput setaf 7``tput sgr0`  "
echo " "
while [ -z "$Bootloader" ]; do
read Bootloader
# Install Chameleon
Sleep 2
cd ./Chameleon/standard/usr/standalone/i386
sudo fdisk -f boot0 -u -y /dev/r"$Bootloader"
sudo dd if=boot1h of=/dev/r"$Bootloader"s2

# Get image file location
  imagepath=`/usr/bin/osascript << EOT
    tell application "Finder"
        activate
        set imagefilepath to choose folder default location "/Volumes" with prompt "Choose your Mac OS X Lion Disk"
    end tell 
    return (posix path of imagefilepath) 
  EOT`

  # Cancel is user selects Cancel
  if [ ! "$imagepath" ] ; then
    osascript -e 'display notification "Program closing" with title "'"$apptitle"'" subtitle "User cancelled"'
    exit 0
  fi

# Copying boot file
echo  "Copying boot file "
sudo cp -Rp boot "$imagepath"
Sleep 1
sudo chflags hidden "$imagepath"/boot
echo "boot file hidden ${3}/boot"

PARENTDIR=$(dirname "$0")
cd "$PARENTDIR"

echo "**********************************************  "
echo "Install Chameleon! "   
echo "**********************************************  "
echo "************ select 1) for PC or 2) for Laptop ************
Type your choice and press Enter."
echo " " 
echo "  1) PC"
echo "  2) lAPTOP"
read n
case $n in
  1) echo "You chose PC"
     echo " "
     sudo cp -Rp ./DVD-PC/* "$imagepath";;
  2) echo "You chose Laptop"
     echo " "
     sudo cp -Rp ./DVD-Lptop/* "$imagepath";;
  *) echo "invalid option";;
esac

install_log="$imagepath"/Extra/Chameleon_Install_Log.txt
# ---------------------------------------------
# Creating log file
# ---------------------------------------------
echo "" > "$install_log"
echo "Chameleon installer log - $( date )" >> "$install_log"
echo "Installer version: Chameleon - Enoch v2.4svn -rev 2923" >> "$install_log"
echo "Built: > By chris1111" >> "$install_log"
echo "Build Xcode  9.2 (9C40b) ( date 2026-05-04 11:25:01 )" >> "$install_log"
echo "======================================================" >> "$install_log"
diskutil list >> "$install_log"

echo "======================================================" >> "${install_log}"
echo "===== Stage 0 loader not written to /dev/"$Bootloader". ======" >> "${install_log}"
echo "===== Written boot1h to /dev/r"$Bootloader"s2. =====" >> "${install_log}"
echo "===== Written boot file on /dev/"$Bootloader"s2. ===" >> "${install_log}"
echo "========== Chameleon Installation Finish ==========" >> "${install_log}"
Sleep 2

sudo cp -Rp ./VoodooHDA/Prefpane/VoodooHDA.prefPane "$imagepath"/Library/PreferencePanes
sudo cp -Rp ./VoodooHDA/Bin/getdump "$imagepath"/usr/local/bin
sudo ./Scripts/Scripts-VoodooHDA/preinstall
sudo cp -Rp ./VoodooHDA/Kext/VoodooHDA.kext "$imagepath"/System/Library/Extensions
sudo cp -Rp ./VoodooHDA/Kext/AppleHDADisabler.kext "$imagepath"/System/Library/Extensions
sudo ./Scripts/Scripts-VoodooHDA/postinstall
# hide usr
sudo chflags hidden "$imagepath"/usr
Sleep 2
osascript -e 'tell app "loginwindow" to «event aevtrrst»'
done
else
Bootloader="$2"
fi





