#!/bin/bash
# VoodooHDA 2.9.0d10

touch "${3}/System/Library/Extensions/"
chmod -R 755 "${3}/System/Library/Extensions/"
chown -R root:wheel "${3}/System/Library/Extensions/" 
kextcache -system-prelinked-kernel
kextcache -system-caches

exit 






